In [2]:
#import dependencies
import pandas as pd

In [3]:
# URls to pull data from
qb_2020_projections = 'https://www.fantasypros.com/nfl/projections/qb.php'

In [13]:
#read table from url
table = pd.read_html(qb_2020_projections, header=1)
table

[                 Player    ATT    CMP     YDS   TDS  INTS  ATT.1  YDS.1  \
 0     Lamar Jackson BAL  468.4  300.8  3480.2  28.8  11.6  159.5  955.2
 1    Patrick Mahomes KC  569.1  371.5  4572.4  34.2  10.7   57.3  297.5
 2      Dak Prescott DAL  572.0  372.4  4495.8  28.9  12.0   60.4  259.1
 3    Deshaun Watson HOU  527.2  346.5  4020.4  26.1  12.7   91.3  496.3
 4    Russell Wilson SEA  491.5  320.9  3892.5  29.6   8.5   71.9  376.6
 ..                  ...    ...    ...     ...   ...   ...    ...    ...
 97       Davis Webb BUF    0.0    0.0     0.0   0.0   0.0    0.0    0.0
 98     Nate Stanley MIN    0.0    0.0     0.0   0.0   0.0    0.0    0.0
 99     Brett Rypien DEN    0.0    0.0     0.0   0.0   0.0    0.0    0.0
 100      Jake Luton JAC    0.0    0.0     0.0   0.0   0.0    0.0    0.0
 101    Easton Stick LAC    0.0    0.0     0.0   0.0   0.0    0.0    0.0

      TDS.1   FL   FPTS
 0      5.9  3.4  355.2
 1      3.0  2.1  341.9
 2      3.7  2.8  314.1
 3      4.6  2.6  312.0
 4      2.3  2.3  303.9
 ..     ...  ...    ...
 97     0.0  0.0    0.0
 98     0.0  0.0    0.0
 99     0.0  0.0    0.0
 100    0.0  0.0    0.0
 101    0.0  0.0    0.0

 [102 rows x 11 columns],    Unnamed: 0  Site Projections  CBS Sports  8/18
 0         NaN  Site Projections        ESPN  8/18
 1         NaN  Site Projections  numberFire  8/18
 2         NaN  Site Projections     FFToday  8/18
 3         NaN  Site Projections     NFL.com  8/09]

In [15]:
QB_2020 = table[0]

QB_2020 = QB_2020.rename(columns={"ATT.1": "RUSH_ATT", "YDS.1": "RUSH_YDS", 'TDS.1': 'RUSH_TDS'})

QB_2020

,Player,ATT,CMP,YDS,TDS,INTS,RUSH_ATT,RUSH_YDS,RUSH_TDS,FL,FPTS
0,Lamar Jackson BAL,468.4,300.8,3480.2,28.8,11.6,159.5,955.2,5.9,3.4,355.2
1,Patrick Mahomes KC,569.1,371.5,4572.4,34.2,10.7,57.3,297.5,3.0,2.1,341.9
2,Dak Prescott DAL,572.0,372.4,4495.8,28.9,12.0,60.4,259.1,3.7,2.8,314.1
3,Deshaun Watson HOU,527.2,346.5,4020.4,26.1,12.7,91.3,496.3,4.6,2.6,312.0
4,Russell Wilson SEA,491.5,320.9,3892.5,29.6,8.5,71.9,376.6,2.3,2.3,303.9
...,...,...,...,...,...,...,...,...,...,...,...
97,Davis Webb BUF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,Nate Stanley MIN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,Brett Rypien DEN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,Jake Luton JAC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101,Easton Stick LAC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# URls to pull data from
qb_2019_stats = 'https://www.fantasypros.com/nfl/stats/qb.php'

#read table from url
table = pd.read_html(qb_2019_stats, header=1)
table
qb_2019 = table[0]

qb_2019 = qb_2019.rename(columns={"ATT.1": "RUSH_ATT", "YDS.1": "RUSH_YDS", 'TD.1': 'RUSH_TDS'})

qb_2019

,Rank,Player,CMP,ATT,PCT,YDS,Y/A,TD,INT,SACKS,RUSH_ATT,RUSH_YDS,RUSH_TDS,FL,G,FPTS,FPTS/G,OWN
0,1,Lamar Jackson (BAL),265,401,66.1,3127,7.8,36,6,23,176,1206,7,2,15,421.7,28.1,100.0%
1,2,Dak Prescott (DAL),388,596,65.1,4902,8.2,30,11,23,52,277,3,2,16,348.9,21.8,98.1%
2,3,Jameis Winston (NO),380,626,60.7,5109,8.2,33,30,47,59,250,1,5,16,335.2,21.0,4.2%
3,4,Russell Wilson (SEA),341,516,66.1,4110,8.0,31,5,48,75,342,3,2,16,333.5,20.8,99.3%
4,5,Deshaun Watson (HOU),333,495,67.3,3852,7.8,26,12,44,82,413,7,3,15,332.0,22.1,99.3%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,135,Tim Boyle (GB),3,4,75.0,15,3.8,0,0,0,5,-7,0,0,3,-0.1,-0.0,0.0%
135,136,Garrett Gilbert (CLE),0,3,0.0,0,0.0,0,0,0,3,-3,0,0,6,-0.3,-0.1,0.0%
136,137,Nick Mullens (SF),0,0,0.0,0,0.0,0,0,0,3,-3,0,0,2,-0.3,-0.2,0.1%
137,138,Jarrett Stidham (NE),2,4,50.0,14,3.5,0,1,1,2,-2,0,0,3,-0.6,-0.2,4.2%
138,139,Blake Bortles (FA),1,2,50.0,3,1.5,0,0,0,2,-9,0,0,4,-0.8,-0.2,0.1%

In [43]:
position_links = []

for position in ['qb', 'wr', 'rb', 'te']:

    stats_2019 = f'https://www.fantasypros.com/nfl/stats/{position}.php'

    position_links.append(stats_2019)

print(len(position_links))

4

In [44]:
position_tables = []

for link in position_links:
    #read table from url
    table = pd.read_html(link, header=1)
    position_tables.append(table)

print(len(position_tables))

4

In [45]:
cleaned_tables = []

for table in position_tables:
    table = table[0]
    cleaned_tables.append(table)

In [46]:
# Clean QB Data

qb_2019 = cleaned_tables[0]

qb_2019 = qb_2019.rename(columns={"ATT.1": "RUSH_ATT", "YDS.1": "RUSH_YDS", 'TD.1': 'RUSH_TDS'})

qb_2019

,Rank,Player,CMP,ATT,PCT,YDS,Y/A,TD,INT,SACKS,RUSH_ATT,RUSH_YDS,RUSH_TDS,FL,G,FPTS,FPTS/G,OWN
0,1,Lamar Jackson (BAL),265,401,66.1,3127,7.8,36,6,23,176,1206,7,2,15,421.7,28.1,100.0%
1,2,Dak Prescott (DAL),388,596,65.1,4902,8.2,30,11,23,52,277,3,2,16,348.9,21.8,98.1%
2,3,Jameis Winston (NO),380,626,60.7,5109,8.2,33,30,47,59,250,1,5,16,335.2,21.0,4.2%
3,4,Russell Wilson (SEA),341,516,66.1,4110,8.0,31,5,48,75,342,3,2,16,333.5,20.8,99.3%
4,5,Deshaun Watson (HOU),333,495,67.3,3852,7.8,26,12,44,82,413,7,3,15,332.0,22.1,99.3%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,135,Tim Boyle (GB),3,4,75.0,15,3.8,0,0,0,5,-7,0,0,3,-0.1,-0.0,0.0%
135,136,Garrett Gilbert (CLE),0,3,0.0,0,0.0,0,0,0,3,-3,0,0,6,-0.3,-0.1,0.0%
136,137,Nick Mullens (SF),0,0,0.0,0,0.0,0,0,0,3,-3,0,0,2,-0.3,-0.2,0.1%
137,138,Jarrett Stidham (NE),2,4,50.0,14,3.5,0,1,1,2,-2,0,0,3,-0.6,-0.2,4.2%
138,139,Blake Bortles (FA),1,2,50.0,3,1.5,0,0,0,2,-9,0,0,4,-0.8,-0.2,0.1%

In [47]:
# Clean RB Data

rb_2019 = cleaned_tables[1]

rb_2019 = rb_2019.rename(columns={"YDS.1": "REC_YDS", 'TD.1': 'REC_TDS'})

rb_2019

,Rank,Player,REC,TGT,YDS,Y/R,LG,20+,TD,ATT,REC_YDS,REC_TDS,FL,G,FPTS,FPTS/G,OWN
0,1,Michael Thomas (NO),149,185,1725,11.6,49,17,9,1,-9,0,0,16,225.6,14.1,100.0%
1,2,Chris Godwin (TB),86,121,1333,15.5,71,25,9,1,8,0,0,14,190.1,13.6,99.9%
2,3,Kenny Golladay (DET),65,116,1190,18.3,75,22,11,0,0,0,1,16,183.0,11.4,99.1%
3,4,Cooper Kupp (LAR),94,134,1161,12.4,66,21,10,2,4,0,0,16,176.5,11.0,97.1%
4,5,Julio Jones (ATL),99,157,1394,14.1,54,21,6,2,-3,0,0,15,175.1,11.7,100.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,455,Darrius Shepherd (GB),1,2,1,1.0,1,0,0,0,0,0,1,6,-1.9,-0.3,0.0%
455,456,Greg Dortch (FA),0,0,0,0.0,0,0,0,0,0,0,1,2,-2.0,-1.0,0.0%
456,457,Ray-Ray McCloud (FA),0,0,0,0.0,0,0,0,0,0,0,1,6,-2.0,-0.3,0.0%
457,458,Quincy Enunwa (FA),1,3,-4,-4.0,8,0,0,0,0,0,1,1,-2.4,-2.4,0.1%
458,459,Michael Walker (JAC),2,3,15,7.5,9,0,0,0,0,0,2,7,-2.5,-0.4,0.0%

In [48]:
# Clean WR Data

wr_2019 = cleaned_tables[2]

wr_2019 = wr_2019.rename(columns={"YDS.1": "RUSH_YDS", 'TD.1': 'RUSH_TDS'})

wr_2019

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,REC,TGT,RUSH_YDS,Y/R,RUSH_TDS,FL,G,FPTS,FPTS/G,OWN
0,1,Christian McCaffrey (CAR),287,1387,4.8,84,6,15,116,142,1005,8.7,4,0,16,355.2,22.2,100.0%
1,2,Derrick Henry (TEN),303,1540,5.1,74,9,16,18,24,206,11.4,2,3,15,276.6,18.4,100.0%
2,3,Aaron Jones (GB),236,1084,4.6,56,5,16,49,68,474,9.7,3,2,16,265.8,16.6,99.9%
3,4,Ezekiel Elliott (DAL),301,1357,4.5,33,4,12,54,71,420,7.8,2,2,16,257.7,16.1,100.0%
4,5,Dalvin Cook (MIN),250,1135,4.5,75,7,13,53,63,519,9.8,0,2,14,239.4,17.1,100.0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,277,David Fluellen (FA),0,0,0.0,0,0,0,0,0,0,0.0,0,0,2,0.0,0.0,0.0%
277,278,Tim Flanders (NO),0,0,0.0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0%
278,279,Jerick McKinnon (SF),0,0,0.0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,9.3%
279,280,Willie Carter (CHI),0,0,0.0,0,0,0,0,0,0,0.0,0,0,0,0.0,0.0,0.0%
280,281,Corey Clement (PHI),0,0,0.0,0,0,0,0,0,0,0.0,0,2,4,-4.0,-1.0,0.3%

In [49]:
# Clean TE Data

te_2019 = cleaned_tables[3]

te_2019 = te_2019.rename(columns={"YDS.1": "RUSH_YDS", 'TD.1': 'RUSH_TDS'})

te_2019

,Rank,Player,REC,TGT,YDS,Y/R,LG,20+,TD,ATT,RUSH_YDS,RUSH_TDS,FL,G,FPTS,FPTS/G,OWN
0,1,Travis Kelce (KC),97,136,1229,12.7,47,13,5,1,4,1,1,16,157.3,9.8,100.0%
1,2,Mark Andrews (BAL),64,98,852,13.3,51,16,10,0,0,0,1,15,143.2,9.5,99.6%
2,3,George Kittle (SF),85,107,1053,12.4,61,16,5,5,22,0,0,14,137.5,9.8,99.9%
3,4,Darren Waller (LV),90,117,1145,12.7,75,14,3,2,5,0,1,16,131.0,8.2,98.4%
4,5,Zach Ertz (PHI),88,135,916,10.4,30,12,6,0,0,0,1,15,127.6,8.5,99.9%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,243,Richard Rodgers (WAS),0,0,0,0.0,0,0,0,0,0,0,0,2,0.0,0.0,0.0%
243,244,Erik Swoope (FA),0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,0.0,0.0%
244,245,Jordan Reed (SF),0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,0.0,0.8%
245,246,Dion Sims (FA),0,0,0,0.0,0,0,0,0,0,0,0,1,0.0,0.0,0.0%
246,247,Connor Davis (NYJ),0,0,0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0%

,1,Harrison Butker (KC),34,38,89.5,56,0,9,9.1,13,3,45,48,16,166.0,10.4,99.9%
0,2,Wil Lutz (NO),32,36,88.9,58,1,9,6,13,3,48,49,16,163.0,10.2,99.2%
1,3,Justin Tucker (BAL),28,29,96.6,51,0,8,9,10,1,57,59,16,153.0,9.6,99.9%
2,4,Matt Gay (TB),27,35,77.1,58,0,6,5,11,5,43,48,16,145.0,9.1,80.0%
3,5,Zane Gonzalez (ARI),31,35,88.6,54,0,12,12,5,2,34,35,16,136.0,8.5,67.3%
4,6,Josh Lambo (JAC),33,34,97.1,56,0,12,9,8,4,19,20,16,134.0,8.4,6.4%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,71,Caleb Sturgis (FA),0,0,0.0,0,0,0,0,0,0,0,0,1,0.0,0.0,0.0%
70,72,Clint Stitser (WAS),0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0%
71,73,Andrew Jacas (SF),0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0%
72,74,Connor Hughes (DAL),0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0%
73,75,Garrett Lindholm (ATL),0,0,0.0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0%